build: off

version: 1.0.3.{build}

branches:
  only:
    - master

skip_commits:
  files:
    - README.md
    - '**/*.ps1'
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

pull_requests:
  do_not_increment_build_number: true

environment:
  NuGetApiKey:
    secure: LaLJPqD3OZAAonFJ+DiolzJ+Z8m0Utm4clo2ePqkvGiCRd6BAEm1UEobZm6JnHOg
  GitHubKey:
    secure: dfugeK+qg0Z61IYqVFdFMt44sCBMBD9Bbjw4TxKoVu8xaoWxwlenG9AVArdsSWXL

install:
- ps: Install-PackageProvider -Name NuGet -Force
- ps: Install-Module -Name posh-git -Force
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
- git config --global user.email "scott@examplenotreal.com"
- git config --global user.name "deathbyvegemite"
- ps: . .\Tests\build.ps1

test_script:


deploy_script:


# on successful build
on_success:
  - do something

# on build failure
on_failure:
  - do something

# after build failure or success
on_finish:
  - do something